// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zrutqbaxwslhsnpifezx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpydXRxYmF4d3NsaHNucGlmZXp4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzNzk0ODgsImV4cCI6MjA3MTk1NTQ4OH0.9yxoaqT-HjK4QqkMbW16P24iwbMz95Q3G86MSr-m9BI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});